// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Clientes
{
    public int Clienteid { get; set; }

    public string Nombrecliente { get; set; }

    public string Apellidocliente { get; set; }

    public DateOnly? FechaNacimientoCliente { get; set; }

    public string Telefonocliente { get; set; }

    public int? TipoDocumentoid { get; set; }

    public string Direccioncliente { get; set; }

    public int? Localidadid { get; set; }

    public string Emailcliente { get; set; }

    public string Documentocliente { get; set; }

    public virtual ICollection<Afiliados> Afiliados { get; set; } = new List<Afiliados>();

    public virtual ICollection<Facturas> Facturas { get; set; } = new List<Facturas>();

    public virtual Localidades Localidad { get; set; }

    public virtual TiposDocumentos TipoDocumento { get; set; }
}