// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Coberturas
{
    public int Coberturaid { get; set; }

    public bool ValidacionObraSocial { get; set; }

    public int? EstadoCoberturaid { get; set; }

    public int? Afiliadoid { get; set; }

    public int? Recetaid { get; set; }

    public virtual Afiliados Afiliado { get; set; }

    public virtual ICollection<DetallesFacturas> DetallesFacturas { get; set; } = new List<DetallesFacturas>();

    public virtual EstadosCoberturas EstadoCobertura { get; set; }

    public virtual Recetas Receta { get; set; }
}