// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Compras
{
    public int Compraid { get; set; }

    public DateTime? FechaCompra { get; set; }

    public int? Empleadoid { get; set; }

    public int? Proveedorid { get; set; }

    public int? Repartidorid { get; set; }

    public int? Sucursalid { get; set; }

    public bool? Activo { get; set; }

    public virtual ICollection<DetallesCompras> DetallesCompras { get; set; } = new List<DetallesCompras>();

    public virtual Empleados Empleado { get; set; }

    public virtual Proveedores Proveedor { get; set; }

    public virtual Repartidores Repartidor { get; set; }

    public virtual Sucursales Sucursal { get; set; }
}