// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Descuentos
{
    public int Descuentoid { get; set; }

    public int? Localidadid { get; set; }

    public DateTime? FechaDescuento { get; set; }

    public int? TipoSuministroid { get; set; }

    public int? ObraSocialid { get; set; }

    public decimal? PorcentajeDescuento { get; set; }

    public int? TipoDescuentoid { get; set; }

    public virtual ICollection<DetallesFacturas> DetallesFacturas { get; set; } = new List<DetallesFacturas>();

    public virtual Localidades Localidad { get; set; }

    public virtual ObrasSociales ObraSocial { get; set; }

    public virtual TiposDescuentos TipoDescuento { get; set; }

    public virtual TiposSuministros TipoSuministro { get; set; }
}