// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class DetallesCompras
{
    public int DetalleCompraid { get; set; }

    public int Compraid { get; set; }

    public int? LoteProductoid { get; set; }

    public string CodigoBarraMedicamentoid { get; set; }

    public string CodigoBarraProductoid { get; set; }

    public int Cantidad { get; set; }

    public int? LoteMedicamentoid { get; set; }

    public bool? Activo { get; set; }

    public virtual Compras Compra { get; set; }

    public virtual LotesMedicamentos LoteMedicamento { get; set; }

    public virtual LotesProductos LoteProducto { get; set; }
}