// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Domain.Models;

public partial class DetallesFacturas
{
    public int NroDetalleid { get; set; }

    public int? Descuentoid { get; set; }

    public int? Productoid { get; set; }

    public int? Medicamentoid { get; set; }

    public int Cantidad { get; set; }

    public decimal? Precio { get; set; }

    public int? Coberturaid { get; set; }

    public int? Facturaid { get; set; }
    [JsonIgnore]
    public virtual Coberturas Cobertura { get; set; }
    [JsonIgnore]
    public virtual Descuentos Descuento { get; set; }
    [JsonIgnore]
    public virtual Facturas Factura { get; set; }
    [JsonIgnore]
    public virtual Medicamentos Medicamento { get; set; }
    [JsonIgnore]
    public virtual Productos Producto { get; set; }
}