// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class DetallesRecetas
{
    public int DetalleRecetaid { get; set; }

    public int Recetaid { get; set; }

    public int Cantidad { get; set; }

    public int? Medicamentoid { get; set; }

    public virtual Medicamentos Medicamento { get; set; }

    public virtual Recetas Receta { get; set; }
}