// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Empleados
{
    public int Empleadoid { get; set; }

    public string Nombreempleado { get; set; }

    public string Apellidoempleado { get; set; }

    public DateOnly? FechaNacimientoEmpleado { get; set; }

    public string Direccionempleado { get; set; }

    public string Telefonoempleado { get; set; }

    public string Emailempleado { get; set; }

    public int? Localidadid { get; set; }

    public int? TipoDocumentoid { get; set; }

    public string Documentoempleado { get; set; }

    public virtual ICollection<Compras> Compras { get; set; } = new List<Compras>();

    public virtual ICollection<EmpleadosSucursales> EmpleadosSucursales { get; set; } = new List<EmpleadosSucursales>();

    public virtual ICollection<Facturas> Facturas { get; set; } = new List<Facturas>();

    public virtual Localidades Localidad { get; set; }

    public virtual TiposDocumentos TipoDocumento { get; set; }
}