// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Domain.Models;

public partial class Facturas
{
    public int Facturaid { get; set; }

    public DateTime? FechaFacturacion { get; set; }

    public int? Empleadoid { get; set; }

    public int? Clienteid { get; set; }

    public int? Sucursalid { get; set; }

    public int? MetodoPagoid { get; set; }
    [JsonIgnore]
    public virtual Clientes Cliente { get; set; }
    [JsonIgnore]
    public virtual ICollection<DetallesFacturas> DetallesFacturas { get; set; } = new List<DetallesFacturas>();
    [JsonIgnore]
    public virtual Empleados Empleado { get; set; }
    [JsonIgnore]
    public virtual MetodosPagos MetodoPago { get; set; }
    [JsonIgnore]
    public virtual Sucursales Sucursal { get; set; }
}