// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Domain.Models;
using Microsoft.EntityFrameworkCore;
using Npgsql;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Domain.Models
{
    public partial class FarmaceuticaContext
    {
        internal readonly object Procedures;
        private IFarmaceuticaContextFunctions _procedures;

        public virtual IFarmaceuticaContextFunctions Functions
        {
            get
            {
                if (_procedures is null) _procedures = new FarmaceuticaContextFunctions(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IFarmaceuticaContextFunctions GetFunctions()
        {
            return Functions;
        }
    }

    public partial class FarmaceuticaContextFunctions : IFarmaceuticaContextFunctions
    {
        private readonly FarmaceuticaContext _context;

        public FarmaceuticaContextFunctions(FarmaceuticaContext context)
        {
            _context = context;
        }

        public virtual async Task<List<sp_ganancias_mensualesResult>> sp_ganancias_mensualesAsync(int? anio, CancellationToken cancellationToken = default)
        {
            var npgsqlParameters = new []
            {
                new NpgsqlParameter
                {
                    ParameterName = "anio",
                    Value = anio ?? Convert.DBNull,
                    NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Integer,
                },
            };
            var _ = await _context.SqlQueryAsync<sp_ganancias_mensualesResult>("SELECT * FROM \"public\".\"sp_ganancias_mensuales\" (@anio)", npgsqlParameters, cancellationToken);

            return _;
        }

        public virtual async Task<List<sp_mpusadosResult>> sp_mpusadosAsync(int? anio, CancellationToken cancellationToken = default)
        {
            var npgsqlParameters = new []
            {
                new NpgsqlParameter
                {
                    ParameterName = "anio",
                    Value = anio ?? Convert.DBNull,
                    NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Integer,
                },
            };
            var _ = await _context.SqlQueryAsync<sp_mpusadosResult>("SELECT * FROM \"public\".\"sp_mpusados\" (@anio)", npgsqlParameters, cancellationToken);

            return _;
        }

        public virtual async Task<List<sp_traer_tablasResult>> sp_traer_tablasAsync(string empleado_dni, string proveedor, string repartidor, string sucursal, CancellationToken cancellationToken = default)
        {
            var npgsqlParameters = new []
            {
                new NpgsqlParameter
                {
                    ParameterName = "empleado_dni",
                    Value = empleado_dni ?? Convert.DBNull,
                    NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Varchar,
                },
                new NpgsqlParameter
                {
                    ParameterName = "proveedor",
                    Value = proveedor ?? Convert.DBNull,
                    NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Varchar,
                },
                new NpgsqlParameter
                {
                    ParameterName = "repartidor",
                    Value = repartidor ?? Convert.DBNull,
                    NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Varchar,
                },
                new NpgsqlParameter
                {
                    ParameterName = "sucursal",
                    Value = sucursal ?? Convert.DBNull,
                    NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Varchar,
                },
            };
            var _ = await _context.SqlQueryAsync<sp_traer_tablasResult>("SELECT * FROM \"public\".\"sp_traer_tablas\" (@empleado_dni, @proveedor, @repartidor, @sucursal)", npgsqlParameters, cancellationToken);

            return _;
        }

        public virtual async Task<List<sp_traer_tablas_detalleResult>> sp_traer_tablas_detalleAsync(string codigobarraproducto, string codigobarramedicamento, int? lotemedicamento, int? loteproducto, CancellationToken cancellationToken = default)
        {
            var npgsqlParameters = new []
            {
                new NpgsqlParameter
                {
                    ParameterName = "codigobarraproducto",
                    Value = codigobarraproducto ?? Convert.DBNull,
                    NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Varchar,
                },
                new NpgsqlParameter
                {
                    ParameterName = "codigobarramedicamento",
                    Value = codigobarramedicamento ?? Convert.DBNull,
                    NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Varchar,
                },
                new NpgsqlParameter
                {
                    ParameterName = "lotemedicamento",
                    Value = lotemedicamento ?? Convert.DBNull,
                    NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Integer,
                },
                new NpgsqlParameter
                {
                    ParameterName = "loteproducto",
                    Value = loteproducto ?? Convert.DBNull,
                    NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Integer,
                },
            };
            var _ = await _context.SqlQueryAsync<sp_traer_tablas_detalleResult>("SELECT * FROM \"public\".\"sp_traer_tablas_detalle\" (@codigobarraproducto, @codigobarramedicamento, @lotemedicamento, @loteproducto)", npgsqlParameters, cancellationToken);

            return _;
        }

        public virtual async Task<List<sp_ventas_por_sucursalResult>> sp_ventas_por_sucursalAsync(int? anio, CancellationToken cancellationToken = default)
        {
            var npgsqlParameters = new []
            {
                new NpgsqlParameter
                {
                    ParameterName = "anio",
                    Value = anio ?? Convert.DBNull,
                    NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Integer,
                },
            };
            var _ = await _context.SqlQueryAsync<sp_ventas_por_sucursalResult>("SELECT * FROM \"public\".\"sp_ventas_por_sucursal\" (@anio)", npgsqlParameters, cancellationToken);

            return _;
        }
    }
}
