// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

public partial class FarmaceuticaContext : DbContext
{
    public FarmaceuticaContext(DbContextOptions<FarmaceuticaContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Afiliados> Afiliados { get; set; }

    public virtual DbSet<ClasificacionesSuministros> ClasificacionesSuministros { get; set; }

    public virtual DbSet<Clientes> Clientes { get; set; }

    public virtual DbSet<Coberturas> Coberturas { get; set; }

    public virtual DbSet<Compras> Compras { get; set; }

    public virtual DbSet<Descuentos> Descuentos { get; set; }

    public virtual DbSet<DetallesCompras> DetallesCompras { get; set; }

    public virtual DbSet<DetallesFacturas> DetallesFacturas { get; set; }

    public virtual DbSet<DetallesRecetas> DetallesRecetas { get; set; }

    public virtual DbSet<Doctores> Doctores { get; set; }

    public virtual DbSet<Empleados> Empleados { get; set; }

    public virtual DbSet<EmpleadosSucursales> EmpleadosSucursales { get; set; }

    public virtual DbSet<EspecialidadesMedicos> EspecialidadesMedicos { get; set; }

    public virtual DbSet<EstadosCoberturas> EstadosCoberturas { get; set; }

    public virtual DbSet<Facturas> Facturas { get; set; }

    public virtual DbSet<InventariosMedicamentos> InventariosMedicamentos { get; set; }

    public virtual DbSet<InventariosProductos> InventariosProductos { get; set; }

    public virtual DbSet<Localidades> Localidades { get; set; }

    public virtual DbSet<LotesMedicamentos> LotesMedicamentos { get; set; }

    public virtual DbSet<LotesProductos> LotesProductos { get; set; }

    public virtual DbSet<Medicamentos> Medicamentos { get; set; }

    public virtual DbSet<MetodosPagos> MetodosPagos { get; set; }

    public virtual DbSet<ObrasSociales> ObrasSociales { get; set; }

    public virtual DbSet<Paises> Paises { get; set; }

    public virtual DbSet<PlanesObrasSociales> PlanesObrasSociales { get; set; }

    public virtual DbSet<Productos> Productos { get; set; }

    public virtual DbSet<Proveedores> Proveedores { get; set; }

    public virtual DbSet<Provincias> Provincias { get; set; }

    public virtual DbSet<Recetas> Recetas { get; set; }

    public virtual DbSet<Repartidores> Repartidores { get; set; }

    public virtual DbSet<Restricciones> Restricciones { get; set; }

    public virtual DbSet<Sucursales> Sucursales { get; set; }

    public virtual DbSet<TiposDescuentos> TiposDescuentos { get; set; }

    public virtual DbSet<TiposDocumentos> TiposDocumentos { get; set; }

    public virtual DbSet<TiposPresentaciones> TiposPresentaciones { get; set; }

    public virtual DbSet<TiposSuministros> TiposSuministros { get; set; }

    public virtual DbSet<UnidadesMedidas> UnidadesMedidas { get; set; }

    public virtual DbSet<Vwmedicamentotop> Vwmedicamentotop { get; set; }

    public virtual DbSet<Vwproductotop> Vwproductotop { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Afiliados>(entity =>
        {
            entity.HasKey(e => e.Afiliadoid).HasName("afiliados_pkey");

            entity.ToTable("afiliados");

            entity.Property(e => e.Afiliadoid)
                .UseIdentityAlwaysColumn()
                .HasColumnName("afiliadoid");
            entity.Property(e => e.Clienteid).HasColumnName("clienteid");
            entity.Property(e => e.PlanObraSocialid).HasColumnName("plan_obra_socialid");

            entity.HasOne(d => d.Cliente).WithMany(p => p.Afiliados)
                .HasForeignKey(d => d.Clienteid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_afiliados_clientes");

            entity.HasOne(d => d.PlanObraSocial).WithMany(p => p.Afiliados)
                .HasForeignKey(d => d.PlanObraSocialid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_afiliados_plan_obra");
        });

        modelBuilder.Entity<ClasificacionesSuministros>(entity =>
        {
            entity.HasKey(e => e.ClasificacionSuministroid).HasName("clasificaciones_suministros_pkey");

            entity.ToTable("clasificaciones_suministros");

            entity.Property(e => e.ClasificacionSuministroid)
                .UseIdentityAlwaysColumn()
                .HasColumnName("clasificacion_suministroid");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(200)
                .HasColumnName("descripcion");
        });

        modelBuilder.Entity<Clientes>(entity =>
        {
            entity.HasKey(e => e.Clienteid).HasName("clientes_pkey");

            entity.ToTable("clientes");

            entity.Property(e => e.Clienteid)
                .UseIdentityAlwaysColumn()
                .HasColumnName("clienteid");
            entity.Property(e => e.Apellidocliente)
                .HasMaxLength(250)
                .HasColumnName("apellidocliente");
            entity.Property(e => e.Direccioncliente)
                .HasMaxLength(500)
                .HasColumnName("direccioncliente");
            entity.Property(e => e.Documentocliente)
                .HasMaxLength(100)
                .HasColumnName("documentocliente");
            entity.Property(e => e.Emailcliente)
                .HasMaxLength(250)
                .HasColumnName("emailcliente");
            entity.Property(e => e.FechaNacimientoCliente).HasColumnName("fecha_nacimiento_cliente");
            entity.Property(e => e.Localidadid).HasColumnName("localidadid");
            entity.Property(e => e.Nombrecliente)
                .HasMaxLength(250)
                .HasColumnName("nombrecliente");
            entity.Property(e => e.Telefonocliente)
                .HasMaxLength(50)
                .HasColumnName("telefonocliente");
            entity.Property(e => e.TipoDocumentoid).HasColumnName("tipo_documentoid");

            entity.HasOne(d => d.Localidad).WithMany(p => p.Clientes)
                .HasForeignKey(d => d.Localidadid)
                .HasConstraintName("fk_clientes_localidades");

            entity.HasOne(d => d.TipoDocumento).WithMany(p => p.Clientes)
                .HasForeignKey(d => d.TipoDocumentoid)
                .HasConstraintName("fk_clientes_tipos_documentos");
        });

        modelBuilder.Entity<Coberturas>(entity =>
        {
            entity.HasKey(e => e.Coberturaid).HasName("coberturas_pkey");

            entity.ToTable("coberturas");

            entity.Property(e => e.Coberturaid)
                .UseIdentityAlwaysColumn()
                .HasColumnName("coberturaid");
            entity.Property(e => e.Afiliadoid).HasColumnName("afiliadoid");
            entity.Property(e => e.EstadoCoberturaid).HasColumnName("estado_coberturaid");
            entity.Property(e => e.Recetaid).HasColumnName("recetaid");
            entity.Property(e => e.ValidacionObraSocial)
                .HasDefaultValue(false)
                .HasColumnName("validacion_obra_social");

            entity.HasOne(d => d.Afiliado).WithMany(p => p.Coberturas)
                .HasForeignKey(d => d.Afiliadoid)
                .HasConstraintName("fk_coberturas_afiliados");

            entity.HasOne(d => d.EstadoCobertura).WithMany(p => p.Coberturas)
                .HasForeignKey(d => d.EstadoCoberturaid)
                .HasConstraintName("fk_coberturas_estados");

            entity.HasOne(d => d.Receta).WithMany(p => p.Coberturas)
                .HasForeignKey(d => d.Recetaid)
                .HasConstraintName("fk_coberturas_recetas");
        });

        modelBuilder.Entity<Compras>(entity =>
        {
            entity.HasKey(e => e.Compraid).HasName("compras_pkey");

            entity.ToTable("compras");

            entity.Property(e => e.Compraid)
                .UseIdentityAlwaysColumn()
                .HasColumnName("compraid");
            entity.Property(e => e.Activo).HasColumnName("activo");
            entity.Property(e => e.Empleadoid).HasColumnName("empleadoid");
            entity.Property(e => e.FechaCompra)
                .HasColumnType("timestamp(3) without time zone")
                .HasColumnName("fecha_compra");
            entity.Property(e => e.Proveedorid).HasColumnName("proveedorid");
            entity.Property(e => e.Repartidorid).HasColumnName("repartidorid");
            entity.Property(e => e.Sucursalid).HasColumnName("sucursalid");

            entity.HasOne(d => d.Empleado).WithMany(p => p.Compras)
                .HasForeignKey(d => d.Empleadoid)
                .HasConstraintName("fk_compras_empleados");

            entity.HasOne(d => d.Proveedor).WithMany(p => p.Compras)
                .HasForeignKey(d => d.Proveedorid)
                .HasConstraintName("fk_compras_proveedores");

            entity.HasOne(d => d.Repartidor).WithMany(p => p.Compras)
                .HasForeignKey(d => d.Repartidorid)
                .HasConstraintName("fk_compras_repartidores");

            entity.HasOne(d => d.Sucursal).WithMany(p => p.Compras)
                .HasForeignKey(d => d.Sucursalid)
                .HasConstraintName("fk_compras_sucursales");
        });

        modelBuilder.Entity<Descuentos>(entity =>
        {
            entity.HasKey(e => e.Descuentoid).HasName("descuentos_pkey");

            entity.ToTable("descuentos");

            entity.Property(e => e.Descuentoid)
                .UseIdentityAlwaysColumn()
                .HasColumnName("descuentoid");
            entity.Property(e => e.FechaDescuento)
                .HasColumnType("timestamp(3) without time zone")
                .HasColumnName("fecha_descuento");
            entity.Property(e => e.Localidadid).HasColumnName("localidadid");
            entity.Property(e => e.ObraSocialid).HasColumnName("obra_socialid");
            entity.Property(e => e.PorcentajeDescuento)
                .HasPrecision(12, 2)
                .HasColumnName("porcentaje_descuento");
            entity.Property(e => e.TipoDescuentoid).HasColumnName("tipo_descuentoid");
            entity.Property(e => e.TipoSuministroid).HasColumnName("tipo_suministroid");

            entity.HasOne(d => d.Localidad).WithMany(p => p.Descuentos)
                .HasForeignKey(d => d.Localidadid)
                .HasConstraintName("fk_descuentos_localidades");

            entity.HasOne(d => d.ObraSocial).WithMany(p => p.Descuentos)
                .HasForeignKey(d => d.ObraSocialid)
                .HasConstraintName("fk_descuentos_obras_sociales");

            entity.HasOne(d => d.TipoDescuento).WithMany(p => p.Descuentos)
                .HasForeignKey(d => d.TipoDescuentoid)
                .HasConstraintName("fk_descuentos_tiposdescuento");

            entity.HasOne(d => d.TipoSuministro).WithMany(p => p.Descuentos)
                .HasForeignKey(d => d.TipoSuministroid)
                .HasConstraintName("fk_descuentos_tiposuministro");
        });

        modelBuilder.Entity<DetallesCompras>(entity =>
        {
            entity.HasKey(e => e.DetalleCompraid).HasName("detalles_compras_pkey");

            entity.ToTable("detalles_compras");

            entity.Property(e => e.DetalleCompraid)
                .UseIdentityAlwaysColumn()
                .HasColumnName("detalle_compraid");
            entity.Property(e => e.Activo).HasColumnName("activo");
            entity.Property(e => e.Cantidad).HasColumnName("cantidad");
            entity.Property(e => e.CodigoBarraMedicamentoid)
                .HasMaxLength(150)
                .HasColumnName("codigo_barra_medicamentoid");
            entity.Property(e => e.CodigoBarraProductoid)
                .HasMaxLength(150)
                .HasColumnName("codigo_barra_productoid");
            entity.Property(e => e.Compraid).HasColumnName("compraid");
            entity.Property(e => e.LoteMedicamentoid).HasColumnName("lote_medicamentoid");
            entity.Property(e => e.LoteProductoid).HasColumnName("lote_productoid");

            entity.HasOne(d => d.Compra).WithMany(p => p.DetallesCompras)
                .HasForeignKey(d => d.Compraid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_detallescompras_compras");

            entity.HasOne(d => d.LoteMedicamento).WithMany(p => p.DetallesCompras)
                .HasForeignKey(d => d.LoteMedicamentoid)
                .HasConstraintName("fk_detallescompras_lotemed");

            entity.HasOne(d => d.LoteProducto).WithMany(p => p.DetallesCompras)
                .HasForeignKey(d => d.LoteProductoid)
                .HasConstraintName("fk_detallescompras_loteprod");
        });

        modelBuilder.Entity<DetallesFacturas>(entity =>
        {
            entity.HasKey(e => e.NroDetalleid).HasName("detalles_facturas_pkey");

            entity.ToTable("detalles_facturas");

            entity.Property(e => e.NroDetalleid)
                .UseIdentityAlwaysColumn()
                .HasColumnName("nro_detalleid");
            entity.Property(e => e.Cantidad).HasColumnName("cantidad");
            entity.Property(e => e.Coberturaid).HasColumnName("coberturaid");
            entity.Property(e => e.Descuentoid).HasColumnName("descuentoid");
            entity.Property(e => e.Facturaid).HasColumnName("facturaid");
            entity.Property(e => e.Medicamentoid).HasColumnName("medicamentoid");
            entity.Property(e => e.Precio)
                .HasPrecision(12, 2)
                .HasColumnName("precio");
            entity.Property(e => e.Productoid).HasColumnName("productoid");

            entity.HasOne(d => d.Cobertura).WithMany(p => p.DetallesFacturas)
                .HasForeignKey(d => d.Coberturaid)
                .HasConstraintName("fk_detfac_coberturas");

            entity.HasOne(d => d.Descuento).WithMany(p => p.DetallesFacturas)
                .HasForeignKey(d => d.Descuentoid)
                .HasConstraintName("fk_detfac_descuentos");

            entity.HasOne(d => d.Factura).WithMany(p => p.DetallesFacturas)
                .HasForeignKey(d => d.Facturaid)
                .HasConstraintName("fk_detfac_facturas");

            entity.HasOne(d => d.Medicamento).WithMany(p => p.DetallesFacturas)
                .HasForeignKey(d => d.Medicamentoid)
                .HasConstraintName("fk_detfac_medicamentos");

            entity.HasOne(d => d.Producto).WithMany(p => p.DetallesFacturas)
                .HasForeignKey(d => d.Productoid)
                .HasConstraintName("fk_detfac_productos");
        });

        modelBuilder.Entity<DetallesRecetas>(entity =>
        {
            entity.HasKey(e => e.DetalleRecetaid).HasName("detalles_recetas_pkey");

            entity.ToTable("detalles_recetas");

            entity.Property(e => e.DetalleRecetaid)
                .UseIdentityAlwaysColumn()
                .HasColumnName("detalle_recetaid");
            entity.Property(e => e.Cantidad).HasColumnName("cantidad");
            entity.Property(e => e.Medicamentoid).HasColumnName("medicamentoid");
            entity.Property(e => e.Recetaid).HasColumnName("recetaid");

            entity.HasOne(d => d.Medicamento).WithMany(p => p.DetallesRecetas)
                .HasForeignKey(d => d.Medicamentoid)
                .HasConstraintName("fk_detrecetas_medicamentos");

            entity.HasOne(d => d.Receta).WithMany(p => p.DetallesRecetas)
                .HasForeignKey(d => d.Recetaid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_detrecetas_recetas");
        });

        modelBuilder.Entity<Doctores>(entity =>
        {
            entity.HasKey(e => e.Doctorid).HasName("doctores_pkey");

            entity.ToTable("doctores");

            entity.Property(e => e.Doctorid)
                .UseIdentityAlwaysColumn()
                .HasColumnName("doctorid");
            entity.Property(e => e.ApellidoDoctor)
                .HasMaxLength(250)
                .HasColumnName("apellido_doctor");
            entity.Property(e => e.Especialidadid).HasColumnName("especialidadid");
            entity.Property(e => e.MatriculaDoctor)
                .HasMaxLength(100)
                .HasColumnName("matricula_doctor");
            entity.Property(e => e.NombreDoctor)
                .HasMaxLength(250)
                .HasColumnName("nombre_doctor");

            entity.HasOne(d => d.Especialidad).WithMany(p => p.Doctores)
                .HasForeignKey(d => d.Especialidadid)
                .HasConstraintName("fk_doctores_especialidades");
        });

        modelBuilder.Entity<Empleados>(entity =>
        {
            entity.HasKey(e => e.Empleadoid).HasName("empleados_pkey");

            entity.ToTable("empleados");

            entity.Property(e => e.Empleadoid)
                .UseIdentityAlwaysColumn()
                .HasColumnName("empleadoid");
            entity.Property(e => e.Apellidoempleado)
                .HasMaxLength(250)
                .HasColumnName("apellidoempleado");
            entity.Property(e => e.Direccionempleado)
                .HasMaxLength(500)
                .HasColumnName("direccionempleado");
            entity.Property(e => e.Documentoempleado)
                .HasMaxLength(100)
                .HasColumnName("documentoempleado");
            entity.Property(e => e.Emailempleado)
                .HasMaxLength(250)
                .HasColumnName("emailempleado");
            entity.Property(e => e.FechaNacimientoEmpleado).HasColumnName("fecha_nacimiento_empleado");
            entity.Property(e => e.Localidadid).HasColumnName("localidadid");
            entity.Property(e => e.Nombreempleado)
                .HasMaxLength(250)
                .HasColumnName("nombreempleado");
            entity.Property(e => e.Telefonoempleado)
                .HasMaxLength(50)
                .HasColumnName("telefonoempleado");
            entity.Property(e => e.TipoDocumentoid).HasColumnName("tipo_documentoid");

            entity.HasOne(d => d.Localidad).WithMany(p => p.Empleados)
                .HasForeignKey(d => d.Localidadid)
                .HasConstraintName("fk_empleados_localidades");

            entity.HasOne(d => d.TipoDocumento).WithMany(p => p.Empleados)
                .HasForeignKey(d => d.TipoDocumentoid)
                .HasConstraintName("fk_empleados_tipos_doc");
        });

        modelBuilder.Entity<EmpleadosSucursales>(entity =>
        {
            entity.HasKey(e => e.EmpleadoSucursalid).HasName("empleados_sucursales_pkey");

            entity.ToTable("empleados_sucursales");

            entity.Property(e => e.EmpleadoSucursalid)
                .UseIdentityAlwaysColumn()
                .HasColumnName("empleado_sucursalid");
            entity.Property(e => e.Empleadoid).HasColumnName("empleadoid");
            entity.Property(e => e.FechaFin)
                .HasColumnType("timestamp(3) without time zone")
                .HasColumnName("fecha_fin");
            entity.Property(e => e.FechaInicio)
                .HasColumnType("timestamp(3) without time zone")
                .HasColumnName("fecha_inicio");
            entity.Property(e => e.Sucursalid).HasColumnName("sucursalid");

            entity.HasOne(d => d.Empleado).WithMany(p => p.EmpleadosSucursales)
                .HasForeignKey(d => d.Empleadoid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_empsuc_empleados");

            entity.HasOne(d => d.Sucursal).WithMany(p => p.EmpleadosSucursales)
                .HasForeignKey(d => d.Sucursalid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_empsuc_sucursales");
        });

        modelBuilder.Entity<EspecialidadesMedicos>(entity =>
        {
            entity.HasKey(e => e.Especialidadid).HasName("especialidades_medicos_pkey");

            entity.ToTable("especialidades_medicos");

            entity.Property(e => e.Especialidadid)
                .UseIdentityAlwaysColumn()
                .HasColumnName("especialidadid");
            entity.Property(e => e.NombreEspecialidad)
                .HasMaxLength(250)
                .HasColumnName("nombre_especialidad");
        });

        modelBuilder.Entity<EstadosCoberturas>(entity =>
        {
            entity.HasKey(e => e.EstadoCoberturaid).HasName("estados_coberturas_pkey");

            entity.ToTable("estados_coberturas");

            entity.Property(e => e.EstadoCoberturaid)
                .UseIdentityAlwaysColumn()
                .HasColumnName("estado_coberturaid");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(250)
                .HasColumnName("descripcion");
        });

        modelBuilder.Entity<Facturas>(entity =>
        {
            entity.HasKey(e => e.Facturaid).HasName("facturas_pkey");

            entity.ToTable("facturas");

            entity.Property(e => e.Facturaid)
                .UseIdentityAlwaysColumn()
                .HasColumnName("facturaid");
            entity.Property(e => e.Clienteid).HasColumnName("clienteid");
            entity.Property(e => e.Empleadoid).HasColumnName("empleadoid");
            entity.Property(e => e.FechaFacturacion)
                .HasColumnType("timestamp(3) without time zone")
                .HasColumnName("fecha_facturacion");
            entity.Property(e => e.MetodoPagoid).HasColumnName("metodo_pagoid");
            entity.Property(e => e.Sucursalid).HasColumnName("sucursalid");

            entity.HasOne(d => d.Cliente).WithMany(p => p.Facturas)
                .HasForeignKey(d => d.Clienteid)
                .HasConstraintName("fk_facturas_clientes");

            entity.HasOne(d => d.Empleado).WithMany(p => p.Facturas)
                .HasForeignKey(d => d.Empleadoid)
                .HasConstraintName("fk_facturas_empleados");

            entity.HasOne(d => d.MetodoPago).WithMany(p => p.Facturas)
                .HasForeignKey(d => d.MetodoPagoid)
                .HasConstraintName("fk_facturas_metodos_pago");

            entity.HasOne(d => d.Sucursal).WithMany(p => p.Facturas)
                .HasForeignKey(d => d.Sucursalid)
                .HasConstraintName("fk_facturas_sucursales");
        });

        modelBuilder.Entity<InventariosMedicamentos>(entity =>
        {
            entity.HasKey(e => e.InventarioMedicamentoid).HasName("inventarios_medicamentos_pkey");

            entity.ToTable("inventarios_medicamentos");

            entity.Property(e => e.InventarioMedicamentoid)
                .UseIdentityAlwaysColumn()
                .HasColumnName("inventario_medicamentoid");
            entity.Property(e => e.Activo).HasColumnName("activo");
            entity.Property(e => e.Medicamentoid).HasColumnName("medicamentoid");
            entity.Property(e => e.StockActual).HasColumnName("stock_actual");
            entity.Property(e => e.StockMinimo).HasColumnName("stock_minimo");
            entity.Property(e => e.Sucursalid).HasColumnName("sucursalid");

            entity.HasOne(d => d.Medicamento).WithMany(p => p.InventariosMedicamentos)
                .HasForeignKey(d => d.Medicamentoid)
                .HasConstraintName("fk_invmed_medicamentos");

            entity.HasOne(d => d.Sucursal).WithMany(p => p.InventariosMedicamentos)
                .HasForeignKey(d => d.Sucursalid)
                .HasConstraintName("fk_invmed_sucursal");
        });

        modelBuilder.Entity<InventariosProductos>(entity =>
        {
            entity.HasKey(e => e.InventariosProductosid).HasName("inventarios_productos_pkey");

            entity.ToTable("inventarios_productos");

            entity.Property(e => e.InventariosProductosid)
                .UseIdentityAlwaysColumn()
                .HasColumnName("inventarios_productosid");
            entity.Property(e => e.Activo).HasColumnName("activo");
            entity.Property(e => e.Productoid).HasColumnName("productoid");
            entity.Property(e => e.StockActual).HasColumnName("stock_actual");
            entity.Property(e => e.StockMinimo).HasColumnName("stock_minimo");
            entity.Property(e => e.Sucursalid).HasColumnName("sucursalid");

            entity.HasOne(d => d.Producto).WithMany(p => p.InventariosProductos)
                .HasForeignKey(d => d.Productoid)
                .HasConstraintName("fk_invprod_productos");

            entity.HasOne(d => d.Sucursal).WithMany(p => p.InventariosProductos)
                .HasForeignKey(d => d.Sucursalid)
                .HasConstraintName("fk_invprod_sucursal");
        });

        modelBuilder.Entity<Localidades>(entity =>
        {
            entity.HasKey(e => e.Localidadid).HasName("localidades_pkey");

            entity.ToTable("localidades");

            entity.Property(e => e.Localidadid)
                .UseIdentityAlwaysColumn()
                .HasColumnName("localidadid");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(250)
                .HasColumnName("descripcion");
            entity.Property(e => e.Provinciaid).HasColumnName("provinciaid");

            entity.HasOne(d => d.Provincia).WithMany(p => p.Localidades)
                .HasForeignKey(d => d.Provinciaid)
                .HasConstraintName("fk_localidades_provincias");
        });

        modelBuilder.Entity<LotesMedicamentos>(entity =>
        {
            entity.HasKey(e => e.LoteMedicamentoid).HasName("lotes_medicamentos_pkey");

            entity.ToTable("lotes_medicamentos");

            entity.Property(e => e.LoteMedicamentoid)
                .UseIdentityAlwaysColumn()
                .HasColumnName("lote_medicamentoid");
            entity.Property(e => e.Cantidad).HasColumnName("cantidad");
            entity.Property(e => e.FechaElaboracion)
                .HasColumnType("timestamp(3) without time zone")
                .HasColumnName("fecha_elaboracion");
            entity.Property(e => e.FechaVencimiento)
                .HasColumnType("timestamp(3) without time zone")
                .HasColumnName("fecha_vencimiento");
            entity.Property(e => e.Medicamentoid).HasColumnName("medicamentoid");

            entity.HasOne(d => d.Medicamento).WithMany(p => p.LotesMedicamentos)
                .HasForeignKey(d => d.Medicamentoid)
                .HasConstraintName("fk_lotesmed_medicamentos");
        });

        modelBuilder.Entity<LotesProductos>(entity =>
        {
            entity.HasKey(e => e.LoteProductoid).HasName("lotes_productos_pkey");

            entity.ToTable("lotes_productos");

            entity.Property(e => e.LoteProductoid)
                .UseIdentityAlwaysColumn()
                .HasColumnName("lote_productoid");
            entity.Property(e => e.Cantidad).HasColumnName("cantidad");
            entity.Property(e => e.FechaElaboracion)
                .HasColumnType("timestamp(3) without time zone")
                .HasColumnName("fecha_elaboracion");
            entity.Property(e => e.FechaVencimiento)
                .HasColumnType("timestamp(3) without time zone")
                .HasColumnName("fecha_vencimiento");
            entity.Property(e => e.Productoid).HasColumnName("productoid");

            entity.HasOne(d => d.Producto).WithMany(p => p.LotesProductos)
                .HasForeignKey(d => d.Productoid)
                .HasConstraintName("fk_lotesprod_productos");
        });

        modelBuilder.Entity<Medicamentos>(entity =>
        {
            entity.HasKey(e => e.Medicamentoid).HasName("medicamentos_pkey");

            entity.ToTable("medicamentos");

            entity.Property(e => e.Medicamentoid)
                .UseIdentityAlwaysColumn()
                .HasColumnName("medicamentoid");
            entity.Property(e => e.Activo).HasColumnName("activo");
            entity.Property(e => e.ClasificacionSuministroid).HasColumnName("clasificacion_suministroid");
            entity.Property(e => e.CodigoBarraMedicamentoid)
                .HasMaxLength(150)
                .HasColumnName("codigo_barra_medicamentoid");
            entity.Property(e => e.NombreMedicamento)
                .HasMaxLength(400)
                .HasColumnName("nombre_medicamento");
            entity.Property(e => e.PrecioMedicamento)
                .HasPrecision(12, 2)
                .HasColumnName("precio_medicamento");
            entity.Property(e => e.Restriccionid).HasColumnName("restriccionid");
            entity.Property(e => e.TipoPresentacionid).HasColumnName("tipo_presentacionid");
            entity.Property(e => e.TipoSuministroid).HasColumnName("tipo_suministroid");
            entity.Property(e => e.UnidadMedidaid).HasColumnName("unidad_medidaid");

            entity.HasOne(d => d.ClasificacionSuministro).WithMany(p => p.Medicamentos)
                .HasForeignKey(d => d.ClasificacionSuministroid)
                .HasConstraintName("fk_medicamentos_clasificacion");

            entity.HasOne(d => d.Restriccion).WithMany(p => p.Medicamentos)
                .HasForeignKey(d => d.Restriccionid)
                .HasConstraintName("fk_medicamentos_restricciones");

            entity.HasOne(d => d.TipoPresentacion).WithMany(p => p.Medicamentos)
                .HasForeignKey(d => d.TipoPresentacionid)
                .HasConstraintName("fk_medicamentos_tipo_presentacion");

            entity.HasOne(d => d.TipoSuministro).WithMany(p => p.Medicamentos)
                .HasForeignKey(d => d.TipoSuministroid)
                .HasConstraintName("fk_medicamentos_tipos_suministro");

            entity.HasOne(d => d.UnidadMedida).WithMany(p => p.Medicamentos)
                .HasForeignKey(d => d.UnidadMedidaid)
                .HasConstraintName("fk_medicamentos_unidad_medida");
        });

        modelBuilder.Entity<MetodosPagos>(entity =>
        {
            entity.HasKey(e => e.MetodoPagoid).HasName("metodos_pagos_pkey");

            entity.ToTable("metodos_pagos");

            entity.Property(e => e.MetodoPagoid)
                .UseIdentityAlwaysColumn()
                .HasColumnName("metodo_pagoid");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(200)
                .HasColumnName("descripcion");
        });

        modelBuilder.Entity<ObrasSociales>(entity =>
        {
            entity.HasKey(e => e.ObraSocialid).HasName("obras_sociales_pkey");

            entity.ToTable("obras_sociales");

            entity.Property(e => e.ObraSocialid)
                .UseIdentityAlwaysColumn()
                .HasColumnName("obra_socialid");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(250)
                .HasColumnName("descripcion");
        });

        modelBuilder.Entity<Paises>(entity =>
        {
            entity.HasKey(e => e.Paisid).HasName("paises_pkey");

            entity.ToTable("paises");

            entity.Property(e => e.Paisid)
                .UseIdentityAlwaysColumn()
                .HasColumnName("paisid");
            entity.Property(e => e.Descripciones)
                .HasMaxLength(200)
                .HasColumnName("descripciones");
        });

        modelBuilder.Entity<PlanesObrasSociales>(entity =>
        {
            entity.HasKey(e => e.PlanObraSocialid).HasName("planes_obras_sociales_pkey");

            entity.ToTable("planes_obras_sociales");

            entity.Property(e => e.PlanObraSocialid)
                .UseIdentityAlwaysColumn()
                .HasColumnName("plan_obra_socialid");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(250)
                .HasColumnName("descripcion");
            entity.Property(e => e.ObraSocialid).HasColumnName("obra_socialid");

            entity.HasOne(d => d.ObraSocial).WithMany(p => p.PlanesObrasSociales)
                .HasForeignKey(d => d.ObraSocialid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_plan_obra_obra_social");
        });

        modelBuilder.Entity<Productos>(entity =>
        {
            entity.HasKey(e => e.Productoid).HasName("productos_pkey");

            entity.ToTable("productos");

            entity.Property(e => e.Productoid)
                .UseIdentityAlwaysColumn()
                .HasColumnName("productoid");
            entity.Property(e => e.Activo).HasColumnName("activo");
            entity.Property(e => e.ClasificacionSuministroid).HasColumnName("clasificacion_suministroid");
            entity.Property(e => e.CodigoBarraProductoid)
                .HasMaxLength(150)
                .HasColumnName("codigo_barra_productoid");
            entity.Property(e => e.NombreProducto)
                .HasMaxLength(400)
                .HasColumnName("nombre_producto");
            entity.Property(e => e.PrecioProducto)
                .HasPrecision(12, 2)
                .HasColumnName("precio_producto");
            entity.Property(e => e.TipoPresentacionid).HasColumnName("tipo_presentacionid");
            entity.Property(e => e.TipoSuministroid).HasColumnName("tipo_suministroid");
            entity.Property(e => e.UnidadMedidaid).HasColumnName("unidad_medidaid");

            entity.HasOne(d => d.ClasificacionSuministro).WithMany(p => p.Productos)
                .HasForeignKey(d => d.ClasificacionSuministroid)
                .HasConstraintName("fk_productos_clasificacion");

            entity.HasOne(d => d.TipoPresentacion).WithMany(p => p.Productos)
                .HasForeignKey(d => d.TipoPresentacionid)
                .HasConstraintName("fk_productos_tipo_presentacion");

            entity.HasOne(d => d.TipoSuministro).WithMany(p => p.Productos)
                .HasForeignKey(d => d.TipoSuministroid)
                .HasConstraintName("fk_productos_tipos_suministro");

            entity.HasOne(d => d.UnidadMedida).WithMany(p => p.Productos)
                .HasForeignKey(d => d.UnidadMedidaid)
                .HasConstraintName("fk_productos_unidad_medida");
        });

        modelBuilder.Entity<Proveedores>(entity =>
        {
            entity.HasKey(e => e.Proveedorid).HasName("proveedores_pkey");

            entity.ToTable("proveedores");

            entity.Property(e => e.Proveedorid)
                .UseIdentityAlwaysColumn()
                .HasColumnName("proveedorid");
            entity.Property(e => e.Activo).HasColumnName("activo");
            entity.Property(e => e.Cuit)
                .HasMaxLength(50)
                .HasColumnName("cuit");
            entity.Property(e => e.Direccionproveedor)
                .HasMaxLength(500)
                .HasColumnName("direccionproveedor");
            entity.Property(e => e.Emailproveedor)
                .HasMaxLength(250)
                .HasColumnName("emailproveedor");
            entity.Property(e => e.Razonsocial)
                .HasMaxLength(250)
                .HasColumnName("razonsocial");
            entity.Property(e => e.Telefonoproveedor)
                .HasMaxLength(50)
                .HasColumnName("telefonoproveedor");
        });

        modelBuilder.Entity<Provincias>(entity =>
        {
            entity.HasKey(e => e.Provinciaid).HasName("provincias_pkey");

            entity.ToTable("provincias");

            entity.Property(e => e.Provinciaid)
                .UseIdentityAlwaysColumn()
                .HasColumnName("provinciaid");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(200)
                .HasColumnName("descripcion");
            entity.Property(e => e.Paisid).HasColumnName("paisid");

            entity.HasOne(d => d.Pais).WithMany(p => p.Provincias)
                .HasForeignKey(d => d.Paisid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_provincias_paises");
        });

        modelBuilder.Entity<Recetas>(entity =>
        {
            entity.HasKey(e => e.Recetaid).HasName("recetas_pkey");

            entity.ToTable("recetas");

            entity.Property(e => e.Recetaid)
                .UseIdentityAlwaysColumn()
                .HasColumnName("recetaid");
            entity.Property(e => e.Afiliadoid).HasColumnName("afiliadoid");
            entity.Property(e => e.Doctorid).HasColumnName("doctorid");
            entity.Property(e => e.Fecha)
                .HasColumnType("timestamp(3) without time zone")
                .HasColumnName("fecha");

            entity.HasOne(d => d.Afiliado).WithMany(p => p.Recetas)
                .HasForeignKey(d => d.Afiliadoid)
                .HasConstraintName("fk_recetas_afiliados");

            entity.HasOne(d => d.Doctor).WithMany(p => p.Recetas)
                .HasForeignKey(d => d.Doctorid)
                .HasConstraintName("fk_recetas_doctores");
        });

        modelBuilder.Entity<Repartidores>(entity =>
        {
            entity.HasKey(e => e.Repartidorid).HasName("repartidores_pkey");

            entity.ToTable("repartidores");

            entity.Property(e => e.Repartidorid)
                .UseIdentityAlwaysColumn()
                .HasColumnName("repartidorid");
            entity.Property(e => e.Apellidorepartidor)
                .HasMaxLength(250)
                .HasColumnName("apellidorepartidor");
            entity.Property(e => e.Emailrepartidor)
                .HasMaxLength(250)
                .HasColumnName("emailrepartidor");
            entity.Property(e => e.Nombrerepartidor)
                .HasMaxLength(250)
                .HasColumnName("nombrerepartidor");
            entity.Property(e => e.Telefonorepartidor)
                .HasMaxLength(50)
                .HasColumnName("telefonorepartidor");
        });

        modelBuilder.Entity<Restricciones>(entity =>
        {
            entity.HasKey(e => e.Restriccionid).HasName("restricciones_pkey");

            entity.ToTable("restricciones");

            entity.Property(e => e.Restriccionid)
                .UseIdentityAlwaysColumn()
                .HasColumnName("restriccionid");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(250)
                .HasColumnName("descripcion");
        });

        modelBuilder.Entity<Sucursales>(entity =>
        {
            entity.HasKey(e => e.Sucursalid).HasName("sucursales_pkey");

            entity.ToTable("sucursales");

            entity.Property(e => e.Sucursalid)
                .UseIdentityAlwaysColumn()
                .HasColumnName("sucursalid");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(250)
                .HasColumnName("descripcion");
            entity.Property(e => e.Direccion)
                .HasMaxLength(500)
                .HasColumnName("direccion");
            entity.Property(e => e.Localidadid).HasColumnName("localidadid");

            entity.HasOne(d => d.Localidad).WithMany(p => p.Sucursales)
                .HasForeignKey(d => d.Localidadid)
                .HasConstraintName("fk_sucursales_localidades");
        });

        modelBuilder.Entity<TiposDescuentos>(entity =>
        {
            entity.HasKey(e => e.TipoDescuentoid).HasName("tipos_descuentos_pkey");

            entity.ToTable("tipos_descuentos");

            entity.Property(e => e.TipoDescuentoid)
                .UseIdentityAlwaysColumn()
                .HasColumnName("tipo_descuentoid");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(250)
                .HasColumnName("descripcion");
        });

        modelBuilder.Entity<TiposDocumentos>(entity =>
        {
            entity.HasKey(e => e.TipoDocumentoid).HasName("tipos_documentos_pkey");

            entity.ToTable("tipos_documentos");

            entity.Property(e => e.TipoDocumentoid)
                .UseIdentityAlwaysColumn()
                .HasColumnName("tipo_documentoid");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(250)
                .HasColumnName("descripcion");
        });

        modelBuilder.Entity<TiposPresentaciones>(entity =>
        {
            entity.HasKey(e => e.TipoPresentacionid).HasName("tipos_presentaciones_pkey");

            entity.ToTable("tipos_presentaciones");

            entity.Property(e => e.TipoPresentacionid)
                .UseIdentityAlwaysColumn()
                .HasColumnName("tipo_presentacionid");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(200)
                .HasColumnName("descripcion");
        });

        modelBuilder.Entity<TiposSuministros>(entity =>
        {
            entity.HasKey(e => e.TipoSuministroid).HasName("tipos_suministros_pkey");

            entity.ToTable("tipos_suministros");

            entity.Property(e => e.TipoSuministroid)
                .UseIdentityAlwaysColumn()
                .HasColumnName("tipo_suministroid");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(200)
                .HasColumnName("descripcion");
        });

        modelBuilder.Entity<UnidadesMedidas>(entity =>
        {
            entity.HasKey(e => e.UnidadMedidaid).HasName("unidades_medidas_pkey");

            entity.ToTable("unidades_medidas");

            entity.Property(e => e.UnidadMedidaid)
                .UseIdentityAlwaysColumn()
                .HasColumnName("unidad_medidaid");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(200)
                .HasColumnName("descripcion");
        });

        modelBuilder.Entity<Vwmedicamentotop>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vwmedicamentotop");

            entity.Property(e => e.Cantidadvendidatotal).HasColumnName("cantidadvendidatotal");
            entity.Property(e => e.Codigodebarra)
                .HasMaxLength(150)
                .HasColumnName("codigodebarra");
            entity.Property(e => e.Nombre)
                .HasMaxLength(400)
                .HasColumnName("nombre");
            entity.Property(e => e.Precioventa)
                .HasPrecision(12, 2)
                .HasColumnName("precioventa");
            entity.Property(e => e.Sucursal)
                .HasMaxLength(250)
                .HasColumnName("sucursal");
        });

        modelBuilder.Entity<Vwproductotop>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vwproductotop");

            entity.Property(e => e.Cantidadvendidatotal).HasColumnName("cantidadvendidatotal");
            entity.Property(e => e.Codigodebarra)
                .HasMaxLength(150)
                .HasColumnName("codigodebarra");
            entity.Property(e => e.Nombre)
                .HasMaxLength(400)
                .HasColumnName("nombre");
            entity.Property(e => e.Precioventa)
                .HasPrecision(12, 2)
                .HasColumnName("precioventa");
            entity.Property(e => e.Sucursal)
                .HasMaxLength(250)
                .HasColumnName("sucursal");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}