// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Domain.Models;
using Microsoft.EntityFrameworkCore;
using Npgsql;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Domain.Models
{
    public partial interface IFarmaceuticaContextFunctions
    {
        Task<List<sp_ganancias_mensualesResult>> sp_ganancias_mensualesAsync(int? anio, CancellationToken cancellationToken = default);
        Task<List<sp_mpusadosResult>> sp_mpusadosAsync(int? anio, CancellationToken cancellationToken = default);
        Task<List<sp_traer_tablasResult>> sp_traer_tablasAsync(string empleado_dni, string proveedor, string repartidor, string sucursal, CancellationToken cancellationToken = default);
        Task<List<sp_traer_tablas_detalleResult>> sp_traer_tablas_detalleAsync(string codigobarraproducto, string codigobarramedicamento, int? lotemedicamento, int? loteproducto, CancellationToken cancellationToken = default);
        Task<List<sp_ventas_por_sucursalResult>> sp_ventas_por_sucursalAsync(int? anio, CancellationToken cancellationToken = default);
    }
}
