// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class InventariosMedicamentos
{
    public int InventarioMedicamentoid { get; set; }

    public int? Sucursalid { get; set; }

    public int? Medicamentoid { get; set; }

    public int? StockMinimo { get; set; }

    public long? StockActual { get; set; }

    public bool? Activo { get; set; }

    public virtual Medicamentos Medicamento { get; set; }

    public virtual Sucursales Sucursal { get; set; }
}