// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class LotesMedicamentos
{
    public int LoteMedicamentoid { get; set; }

    public int? Medicamentoid { get; set; }

    public DateTime? FechaVencimiento { get; set; }

    public DateTime? FechaElaboracion { get; set; }

    public long? Cantidad { get; set; }

    public virtual ICollection<DetallesCompras> DetallesCompras { get; set; } = new List<DetallesCompras>();

    public virtual Medicamentos Medicamento { get; set; }
}