// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Medicamentos
{
    public int Medicamentoid { get; set; }

    public string CodigoBarraMedicamentoid { get; set; }

    public string NombreMedicamento { get; set; }

    public decimal? PrecioMedicamento { get; set; }

    public int? UnidadMedidaid { get; set; }

    public int? TipoPresentacionid { get; set; }

    public int? ClasificacionSuministroid { get; set; }

    public int? TipoSuministroid { get; set; }

    public int? Restriccionid { get; set; }

    public bool? Activo { get; set; }

    public virtual ClasificacionesSuministros ClasificacionSuministro { get; set; }

    public virtual ICollection<DetallesFacturas> DetallesFacturas { get; set; } = new List<DetallesFacturas>();

    public virtual ICollection<DetallesRecetas> DetallesRecetas { get; set; } = new List<DetallesRecetas>();

    public virtual ICollection<InventariosMedicamentos> InventariosMedicamentos { get; set; } = new List<InventariosMedicamentos>();

    public virtual ICollection<LotesMedicamentos> LotesMedicamentos { get; set; } = new List<LotesMedicamentos>();

    public virtual Restricciones Restriccion { get; set; }

    public virtual TiposPresentaciones TipoPresentacion { get; set; }

    public virtual TiposSuministros TipoSuministro { get; set; }

    public virtual UnidadesMedidas UnidadMedida { get; set; }
}