// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class PlanesObrasSociales
{
    public int PlanObraSocialid { get; set; }

    public string Descripcion { get; set; }

    public int ObraSocialid { get; set; }

    public virtual ICollection<Afiliados> Afiliados { get; set; } = new List<Afiliados>();

    public virtual ObrasSociales ObraSocial { get; set; }
}