// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Proveedores
{
    public int Proveedorid { get; set; }

    public string Razonsocial { get; set; }

    public string Cuit { get; set; }

    public string Direccionproveedor { get; set; }

    public string Telefonoproveedor { get; set; }

    public string Emailproveedor { get; set; }

    public bool? Activo { get; set; }

    public virtual ICollection<Compras> Compras { get; set; } = new List<Compras>();
}