// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Recetas
{
    public int Recetaid { get; set; }

    public DateTime? Fecha { get; set; }

    public int? Afiliadoid { get; set; }

    public int? Doctorid { get; set; }

    public virtual Afiliados Afiliado { get; set; }

    public virtual ICollection<Coberturas> Coberturas { get; set; } = new List<Coberturas>();

    public virtual ICollection<DetallesRecetas> DetallesRecetas { get; set; } = new List<DetallesRecetas>();

    public virtual Doctores Doctor { get; set; }
}