// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Repartidores
{
    public int Repartidorid { get; set; }

    public string Nombrerepartidor { get; set; }

    public string Apellidorepartidor { get; set; }

    public string Telefonorepartidor { get; set; }

    public string Emailrepartidor { get; set; }

    public virtual ICollection<Compras> Compras { get; set; } = new List<Compras>();
}