// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Models
{
    public partial class sp_mpusadosResult
    {
        public string metodo_pago { get; set; }
        public long? cantidadmpusado { get; set; }
        public decimal? porcentaje { get; set; }
    }
}
