// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Models
{
    public partial class sp_traer_tablasResult
    {
        public int? empleadoid { get; set; }
        public int? proveedorid { get; set; }
        public int? repartidorid { get; set; }
        public int? sucursalid { get; set; }
    }
}
