// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Models
{
    public partial class sp_traer_tablas_detalleResult
    {
        public string codigobarraproductoreturn { get; set; }
        public string codigobarramedicamentoreturn { get; set; }
        public int? lotemedicamentoreturn { get; set; }
        public int? loteproductoreturn { get; set; }
    }
}
