// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Models
{
    public partial class sp_ventas_por_sucursalResult
    {
        public string sucursal { get; set; }
        public long? cantidadsucursal { get; set; }
        public decimal? porcentaje { get; set; }
    }
}
