// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Vwproductotop
{
    public string Nombre { get; set; }

    public string Codigodebarra { get; set; }

    public decimal? Precioventa { get; set; }

    public string Sucursal { get; set; }

    public long? Cantidadvendidatotal { get; set; }
}